services:
  db:
    container_name: arcanimal_db
    image: postgres:16
    ports:
      - "9668:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    networks:
      - arcanimal_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    container_name: arcanimal_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - arcanimal_network
    volumes:
      - ./src:/usr/src/app/src
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - db
    restart: always
    env_file:
      - .env

networks:
  arcanimal_network:

volumes:
  postgres_data: